const msg = {
  TIME_FORMAT: `[TIME] TIME LENGTH IS NOT 5. FORMAT HAS TO BE 'HH:MM'`,
  TIME_DELIMETER: `[TIME] DELIMETER SHOULD BE ':' IN 3RD CHARACTER`,
  TIME_HOUR_RANGE: `[TIME] HOUR HAS TO BE BETWEEN 00 to 23`,
  TIME_MINUTE_RANGE: `[TIME] MINUTS HAS TO BE BETWEEN 00 to 59`,
  TIME_DIV_RANGE: `[TIME] divTime HAS TO BE  1,2,3,5,6,10,12,15,20,30, or 60`,
  // About Shift
  SHIFT_RANGE: `[SHIFT] TIME LENGTH IS NOT 11. FORMAT HAS TO BE 'HH:MM-HH:MM'`,
  SHIFT_DELIMETER: `[SHIFT] DELIMETER SHOULD BE '-' IN 6TH CHARACTER`,
  // About Data Type
  DATA_NOT_STRING: `[DATA] HAS TO BE STRING`,
  DATA_NOT_NUMBER: `[DATA] HAS TO BE NUMBER`,
  DATA_NOT_BOOLEAN: `[DATA] HAS TO BE BOOLEAN`,
  // Required
  REQUIRED: str => `${str} IS NECESSARY`
}

export default msg